version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      TZ: Europe/Amsterdam
      POSTGRES_DB: CalenderAppDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev123password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5222:5432"

  backend:
    build:
      context: ./Server/Server
    container_name: backend
    depends_on:
      - postgres
    env_file:
      - ./Server/Server/.env
    environment:
      TZ: Europe/Amsterdam
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__db: Host=postgres;Database=CalenderAppDB;Username=postgres;Password=dev123password
    ports:
      - "5005:8080"

  frontend:
    build:
      context: ./app
      args:
        VITE_API_URL: http://backend:8080
    container_name: frontend
    depends_on:
      - backend
    environment:
      TZ: Europe/Amsterdam
    ports:
      - "5173:80"

volumes:
  postgres_data: